// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notification.proto

package notification

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushMessageRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Event                string   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMessageRequest) Reset()         { *m = PushMessageRequest{} }
func (m *PushMessageRequest) String() string { return proto.CompactTextString(m) }
func (*PushMessageRequest) ProtoMessage()    {}
func (*PushMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{0}
}

func (m *PushMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMessageRequest.Unmarshal(m, b)
}
func (m *PushMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMessageRequest.Marshal(b, m, deterministic)
}
func (m *PushMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMessageRequest.Merge(m, src)
}
func (m *PushMessageRequest) XXX_Size() int {
	return xxx_messageInfo_PushMessageRequest.Size(m)
}
func (m *PushMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushMessageRequest proto.InternalMessageInfo

func (m *PushMessageRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *PushMessageRequest) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *PushMessageRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type PushMessageResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMessageResponse) Reset()         { *m = PushMessageResponse{} }
func (m *PushMessageResponse) String() string { return proto.CompactTextString(m) }
func (*PushMessageResponse) ProtoMessage()    {}
func (*PushMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{1}
}

func (m *PushMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMessageResponse.Unmarshal(m, b)
}
func (m *PushMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMessageResponse.Marshal(b, m, deterministic)
}
func (m *PushMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMessageResponse.Merge(m, src)
}
func (m *PushMessageResponse) XXX_Size() int {
	return xxx_messageInfo_PushMessageResponse.Size(m)
}
func (m *PushMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushMessageResponse proto.InternalMessageInfo

func (m *PushMessageResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PushMessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*PushMessageRequest)(nil), "notification.PushMessageRequest")
	proto.RegisterType((*PushMessageResponse)(nil), "notification.PushMessageResponse")
}

func init() {
	proto.RegisterFile("notification.proto", fileDescriptor_736a457d4a5efa07)
}

var fileDescriptor_736a457d4a5efa07 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0xcb, 0x2f, 0xc9,
	0x4c, 0xcb, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x41, 0x16, 0x53, 0x0a, 0xe3, 0x12, 0x0a, 0x28, 0x2d, 0xce, 0xf0, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c,
	0x4f, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe3, 0x62, 0x2b, 0x2d, 0x4e, 0x2d,
	0xf2, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x84, 0x44, 0xb8, 0x58, 0x53,
	0xcb, 0x52, 0xf3, 0x4a, 0x24, 0x98, 0xc0, 0xc2, 0x10, 0x8e, 0x90, 0x10, 0x17, 0x4b, 0x4a, 0x62,
	0x49, 0xa2, 0x04, 0x33, 0x58, 0x10, 0xcc, 0x56, 0x72, 0xe6, 0x12, 0x46, 0x31, 0xb7, 0xb8, 0x20,
	0x3f, 0xaf, 0x38, 0x15, 0xa4, 0x34, 0x39, 0x3f, 0x25, 0x15, 0x6c, 0x2c, 0x6b, 0x10, 0x98, 0x2d,
	0x24, 0xc1, 0xc5, 0x9e, 0x0b, 0x51, 0x06, 0x35, 0x16, 0xc6, 0x35, 0xca, 0xe4, 0x12, 0xf6, 0x43,
	0x72, 0x6c, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x50, 0x10, 0x17, 0x37, 0x92, 0xd9, 0x42,
	0x0a, 0x7a, 0x28, 0xbe, 0xc4, 0xf4, 0x8e, 0x94, 0x22, 0x1e, 0x15, 0x10, 0x87, 0x25, 0xb1, 0x81,
	0x03, 0xc7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xc1, 0x6a, 0xd5, 0x32, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificationServiceClient interface {
	PushMessage(ctx context.Context, in *PushMessageRequest, opts ...grpc.CallOption) (*PushMessageResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) PushMessage(ctx context.Context, in *PushMessageRequest, opts ...grpc.CallOption) (*PushMessageResponse, error) {
	out := new(PushMessageResponse)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/PushMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
type NotificationServiceServer interface {
	PushMessage(context.Context, *PushMessageRequest) (*PushMessageResponse, error)
}

// UnimplementedNotificationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNotificationServiceServer struct {
}

func (*UnimplementedNotificationServiceServer) PushMessage(ctx context.Context, req *PushMessageRequest) (*PushMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushMessage not implemented")
}

func RegisterNotificationServiceServer(s *grpc.Server, srv NotificationServiceServer) {
	s.RegisterService(&_NotificationService_serviceDesc, srv)
}

func _NotificationService_PushMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).PushMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.NotificationService/PushMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).PushMessage(ctx, req.(*PushMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NotificationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "notification.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushMessage",
			Handler:    _NotificationService_PushMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}
